package fmi.sports.tournament.organizer.backend.response;

public enum ResponseResult {

    SUCCESSFULLY_CREATED,
    SUCCESSFULLY_UPDATED,
    SUCCESSFULLY_DELETED,
    SUCCESSFULLY_FOUND,
    TOURNAMENT_ALREADY_STARTED_OR_FINISHED,
    TEAM_ALREADY_REGISTERED,
    NO_MORE_PLACES_AVAILABLE,
    INSUFFICIENT_MONEY,
    SUCCESSFULLY_REGISTERED,
    SUCCESSFULLY_UNREGISTERED,
    ID_NOT_FOUND,
    SUCCESSFULLY_SCHEDULED,
    TEAM_NOT_PARTICIPATING_IN_TOURNAMENT,
    MATCH_ALREADY_COMPLETED,
    USER_ALREADY_EXISTS
}
